### PR TITLE
Add Chaperone Automations

### PR DESCRIPTION
**Pull request by TheMrGong**
Adds an automation for automatically adjusting SteamVR's activation distance

Found myself having to go into OpenVR and toggle off chaperone manually so it wouldn't randomly flash while I was asleep.

Not sure how you/if you want the README updated

### CODE REVIEW

**Comment by Raphiiko** [comment]
I had a very brief look and overall this looks great! Thanks a lot for contributing! ^^

I personally keep my chaperone disabled so I've never run into this issue, but I can imagine that for those who don't this can be a very useful automation.

I'll take a more proper look somewhere (end of) this week to see if we can get this merged!

**Comment by TheMrGong** [comment]
You're welcome! My room only meets absolute minimum required for room space so I need to have chaperone on otherwise my walls would gain some new holes ^^"

I hope the PR is okay, I mostly copied the existing template of the Resolution Automation and looked at what values OpenVR Advanced Setting was updating - html is most definitely not my forte

**Comment by Raphiiko** [comment]
It looks pretty much good as is! I'll give it a quick test and get it in with the next release. Thanks a lot again :)

If I add credit anywhere, I'll assume I can use "TheMrGong" for your name and your github profile for any link. 
If you want me to change the name, or the link to something like your Twitter, please let me know!

**Comment by TheMrGong** [comment]
I'd prefer gongo if possible ^^"
Sorry for the late reply, I didn't get any notifications for this PR being merged

**Comment by Raphiiko** [comment]
Gotcha, I'll change it before the next release！

**Pull request merged**
